//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnerEquipment
    {
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public bool DeriKoltuk { get; set; }
        public bool KumasKoltuk { get; set; }
        public bool Deri_KumasKoltuk { get; set; }
        public bool ElektrikliOnCamlar { get; set; }
        public bool ElektrikliArkaCamlar { get; set; }
        public bool Klima_Analog { get; set; }
        public bool Klima_Digital { get; set; }
        public bool OtmKararanDikizAynasi { get; set; }
        public bool OnKolDayama { get; set; }
        public bool ArkaKolDayama { get; set; }
        public bool AnahtarsizCalistirma { get; set; }
        public bool AltiIleriVites { get; set; }
        public bool YediIleriVites { get; set; }
        public bool HidrolikDireksiyon { get; set; }
        public bool FonksiyonelDireksiyon { get; set; }
        public bool AyarlanabilirDireksiyon { get; set; }
        public bool DeriDireksiyon { get; set; }
        public bool AhsapDireksiyon { get; set; }
        public bool IsitmaliDireksiyon { get; set; }
        public bool Koltuklar_Elektirkli { get; set; }
        public bool Koltuklar_Hafizali { get; set; }
        public bool Koltuklar_Katlanır { get; set; }
        public bool Koltuklar_OnIsitmali { get; set; }
        public bool Koltuklar_ArkaIsitmali { get; set; }
        public bool Koltuklar_Sogutmali { get; set; }
        public bool HizSabitleyici { get; set; }
        public bool AdaptiveCruiseControl { get; set; }
        public bool SogutmaliTorpido { get; set; }
        public bool YolBilgisayari { get; set; }
        public bool KromKaplama { get; set; }
        public bool AhsapKapama { get; set; }
        public bool HeadUpDisplay { get; set; }
        public bool Start_Stop { get; set; }
        public bool GeceGorusKamerasi { get; set; }
        public bool OnGorusKamerasi { get; set; }
        public bool UcuncuSiraKoltuk { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
