//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ONROtomotivEntities : DbContext
    {
        public ONROtomotivEntities()
            : base("name=ONROtomotivEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BodyType> BodyTypes { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<ComparedVehicle> ComparedVehicles { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Damage> Damages { get; set; }
        public virtual DbSet<FuelType> FuelTypes { get; set; }
        public virtual DbSet<InnerEquipment> InnerEquipments { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Multimedia> Multimedias { get; set; }
        public virtual DbSet<OuterEquipment> OuterEquipments { get; set; }
        public virtual DbSet<PaypmentStatu> PaypmentStatus { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<RentedPaypment> RentedPaypments { get; set; }
        public virtual DbSet<RentInfo> RentInfos { get; set; }
        public virtual DbSet<RentOrder> RentOrders { get; set; }
        public virtual DbSet<SaleInfo> SaleInfos { get; set; }
        public virtual DbSet<SecuritySpec> SecuritySpecs { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<SoldOrder> SoldOrders { get; set; }
        public virtual DbSet<SoldPaypment> SoldPaypments { get; set; }
        public virtual DbSet<Sub_Model> Sub_Model { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransmissionType> TransmissionTypes { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<WheelDriveType> WheelDriveTypes { get; set; }
    }
}
