//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multimedia
    {
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public bool Radyo_Kasetçalar { get; set; }
        public bool Radyo_CDCalar { get; set; }
        public bool Radyo_MP3Calar { get; set; }
        public bool TV_Navigasyon { get; set; }
        public bool Bluetooth_Telefon { get; set; }
        public bool USB_AUX { get; set; }
        public bool AUX { get; set; }
        public bool iPodBaglantisi { get; set; }
        public bool AltiArtiHoparlor { get; set; }
        public bool CDDegistirici { get; set; }
        public bool ArkaEglencePaketi { get; set; }
        public bool DVDDegistirici { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
