//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OuterEquipment
    {
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public bool Hardtop { get; set; }
        public bool Far_LED { get; set; }
        public bool Far_Halojen { get; set; }
        public bool Far_Xenon { get; set; }
        public bool Far_BiXenon { get; set; }
        public bool Far_Sis { get; set; }
        public bool Far_Adaptif { get; set; }
        public bool FarGeceSensoru { get; set; }
        public bool Far_Yikama { get; set; }
        public bool Aynalar_Elektrikli { get; set; }
        public bool Aynalar_Katlanir { get; set; }
        public bool Aynalar_Isitmali { get; set; }
        public bool Aynalar_Hafizali { get; set; }
        public bool ParkSensoru_Arka { get; set; }
        public bool ParkSensoru_On { get; set; }
        public bool AlasimliJant { get; set; }
        public bool Sunroof { get; set; }
        public bool PanoramikCamTavan { get; set; }
        public bool YagmurSensoru { get; set; }
        public bool ArkaCamBuzCozucu { get; set; }
        public bool PanoramikOnCam { get; set; }
        public bool RomorkCekiDemiri { get; set; }
        public bool AkilliBagajKapagi { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
