//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentedPaypment
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int RentedOrdersID { get; set; }
        public decimal CustomerPaypmentMade { get; set; }
        public System.DateTime CustomerPaypmentMadeDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RentOrder RentOrder { get; set; }
    }
}
