//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentOrder()
        {
            this.RentedPaypments = new HashSet<RentedPaypment>();
        }
    
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public int CustomerID { get; set; }
        public decimal RentedPrice { get; set; }
        public System.DateTime RentalStartDate { get; set; }
        public System.DateTime RentalEndDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentedPaypment> RentedPaypments { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
