//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuritySpec
    {
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public bool ABC { get; set; }
        public bool ABS { get; set; }
        public bool ASR { get; set; }
        public bool ESP { get; set; }
        public bool Airmatic { get; set; }
        public bool EDL { get; set; }
        public bool EBA { get; set; }
        public bool EBD { get; set; }
        public bool TSC { get; set; }
        public bool BAS { get; set; }
        public bool Distronic { get; set; }
        public bool YokusKalkisDestegi { get; set; }
        public bool GeceGorus { get; set; }
        public bool SerittenAyrilmaIkazi { get; set; }
        public bool SeritDegistirmeYardimcisi { get; set; }
        public bool Airbag_Surucu { get; set; }
        public bool Airbag_Yolcu { get; set; }
        public bool Airbag_Yan { get; set; }
        public bool Airbag_Diz { get; set; }
        public bool Airbag_Perde { get; set; }
        public bool Airbag_Tavan { get; set; }
        public bool KorNoktaUyariSistemi { get; set; }
        public bool LastikArizaGostergesi { get; set; }
        public bool YorgunlukTespitSistemi { get; set; }
        public bool Isofix { get; set; }
        public bool Alarm { get; set; }
        public bool MerkeziKilit { get; set; }
        public bool Immobilizer { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
