//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldPaypment
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int SoldOrdersID { get; set; }
        public int PaypmentStatusID { get; set; }
        public decimal CustomersPaypmentMade { get; set; }
        public decimal CustomerPaypmentDue { get; set; }
        public System.DateTime CustomersPaypmentMadeDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PaypmentStatu PaypmentStatu { get; set; }
        public virtual SoldOrder SoldOrder { get; set; }
    }
}
