//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONROtomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.ComparedVehicles = new HashSet<ComparedVehicle>();
            this.Damages = new HashSet<Damage>();
            this.InnerEquipments = new HashSet<InnerEquipment>();
            this.Multimedias = new HashSet<Multimedia>();
            this.OuterEquipments = new HashSet<OuterEquipment>();
            this.Photos = new HashSet<Photo>();
            this.RentInfos = new HashSet<RentInfo>();
            this.RentInfos1 = new HashSet<RentInfo>();
            this.RentOrders = new HashSet<RentOrder>();
            this.SaleInfos = new HashSet<SaleInfo>();
            this.SecuritySpecs = new HashSet<SecuritySpec>();
            this.SoldOrders = new HashSet<SoldOrder>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int BrandID { get; set; }
        public int SerieID { get; set; }
        public int ModelID { get; set; }
        public int Sub_ModelID { get; set; }
        public int FuelTypeID { get; set; }
        public int TransmissionTypeID { get; set; }
        public int BodyTypeID { get; set; }
        public int WheelDriveTypeID { get; set; }
        public int ColorID { get; set; }
        public string ProductName { get; set; }
        public int Year { get; set; }
        public System.DateTime ListingDate { get; set; }
        public int KM { get; set; }
        public int EngineCapacity { get; set; }
        public int EngineHP { get; set; }
        public bool Warranty { get; set; }
        public string Region { get; set; }
        public bool Trade { get; set; }
        public bool Condition { get; set; }
        public string Description { get; set; }
        public string MasterPhotoPath { get; set; }
    
        public virtual BodyType BodyType { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComparedVehicle> ComparedVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage> Damages { get; set; }
        public virtual FuelType FuelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnerEquipment> InnerEquipments { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Multimedia> Multimedias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OuterEquipment> OuterEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentInfo> RentInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentInfo> RentInfos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentOrder> RentOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleInfo> SaleInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuritySpec> SecuritySpecs { get; set; }
        public virtual Series Series { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoldOrder> SoldOrders { get; set; }
        public virtual Sub_Model Sub_Model { get; set; }
        public virtual TransmissionType TransmissionType { get; set; }
        public virtual WheelDriveType WheelDriveType { get; set; }
    }
}
